dist: trusty
sudo: false

language: node_js
node_js:
  - '12'

cache:
  directories:
    - ./node_modules

install:
  - npm install
  - npm install puppeteer

script:
  - npm run test:ci

jobs:
  include:
    - stage: deploy
      install: skip
      script: echo "Running tests ..."
      if: tag IS present
